fix: Have wlink return proper bitvec sizes
This fixes a regression introduced by
ff8cace3d4e57dc0bf68f9bd453b8ee7ddf28f71 BitVec: the sequel (#3236)

The following panic is shown using a wlink probe on an amd64 system.

thread 'tokio-runtime-worker' panicked at /home/arthur/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bitvec-1.0.1/src/field.rs:526:2:
cannot load 32 bits from a 64-bit region

Return the requested bitvec size rather than whathever usize is.

Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>

Add changelog

Signed-off-by: Arthur Heymans <arthur@aheymans.xyz>